# 功能性操作符

```
    /**
     * 使得被观察者延迟一段时间再发送事件
     */
    private void rxjavaDelay() {
        // 1. 指定延迟时间
        // 参数1 = 时间；参数2 = 时间单位
        //delay( long delay, TimeUnit unit)

        // 2. 指定延迟时间 & 调度器
        // 参数1 = 时间；参数2 = 时间单位；参数3 = 线程调度器
        //delay( long delay, TimeUnit unit, mScheduler scheduler)

        // 3. 指定延迟时间  & 错误延迟
        // 错误延迟，即：若存在Error事件，则如常执行，执行后再抛出错误异常
        // 参数1 = 时间；参数2 = 时间单位；参数3 = 错误延迟参数
        //delay( long delay, TimeUnit unit,boolean delayError)

        // 4. 指定延迟时间 & 调度器 & 错误延迟
        // 参数1 = 时间；参数2 = 时间单位；参数3 = 线程调度器；参数4 = 错误延迟参数
        //delay( long delay, TimeUnit unit, mScheduler scheduler,boolean delayError):指定延迟多长时间并添加调度器，
        //错误通知可以设置是否延迟
    }

    /**
     * 在某个事件的生命周期中调用
     */
    private void rxjavaDo() {
        Observable.create(new ObservableOnSubscribe<Integer>() {
            @Override
            public void subscribe(ObservableEmitter<Integer> e) throws Exception {
                e.onNext(1);
                e.onNext(2);
                e.onNext(3);
                e.onError(new Throwable("发生错误了"));
            }
        })
                // 1. 当Observable每发送1次数据事件就会调用1次
                .doOnEach(new Consumer<Notification<Integer>>() {
                    @Override
                    public void accept(Notification<Integer> integerNotification) throws Exception {
                        System.out.println("doOnEach: " + integerNotification.getValue());
                    }
                })
                // 2. 执行Next事件前调用
                .doOnNext(new Consumer<Integer>() {
                    @Override
                    public void accept(Integer integer) throws Exception {
                        System.out.println("doOnNext: " + integer);
                    }
                })
                // 3. 执行Next事件后调用
                .doAfterNext(new Consumer<Integer>() {
                    @Override
                    public void accept(Integer integer) throws Exception {
                        System.out.println("doAfterNext: " + integer);
                    }
                })
                // 4. Observable正常发送事件完毕后调用
                .doOnComplete(new Action() {
                    @Override
                    public void run() throws Exception {
                        System.out.println("doOnComplete: ");
                    }
                })
                // 5. Observable发送错误事件时调用
                .doOnError(new Consumer<Throwable>() {
                    @Override
                    public void accept(Throwable throwable) throws Exception {
                        System.out.println("doOnError: " + throwable.getMessage());
                    }
                })
                // 6. 观察者订阅时调用
                .doOnSubscribe(new Consumer<Disposable>() {
                    @Override
                    public void accept(@NonNull Disposable disposable) throws Exception {
                        System.out.println("doOnSubscribe: ");
                    }
                })
                // 7. Observable发送事件完毕后调用，无论正常发送完毕 / 异常终止
                .doAfterTerminate(new Action() {
                    @Override
                    public void run() throws Exception {
                        System.out.println("doAfterTerminate: ");
                    }
                })
                // 8. 最后执行
                .doFinally(new Action() {
                    @Override
                    public void run() throws Exception {
                        System.out.println("doFinally: ");
                    }
                })
                .subscribe(new Observer<Integer>() {
                    @Override
                    public void onSubscribe(Disposable d) {

                    }

                    @Override
                    public void onNext(Integer value) {
                        System.out.println("接收到了事件" + value);
                    }

                    @Override
                    public void onError(Throwable e) {
                        System.out.println("对Error事件作出响应");
                    }

                    @Override
                    public void onComplete() {
                        System.out.println("对Complete事件作出响应");
                    }
                });
    }

    /**
     * 重试，即出现错误，让被观察者重新发送数据
     */
    private void rxjavaRetry() {
            /*
                1. retry（）
                作用：出现错误时，让被观察者重新发送数据
                注：若一直错误，则一直重新发送

                2. retry（long time）
                作用：出现错误时，让被观察者重新发送数据（具备重试次数限制
                参数 = 重试次数

                3. retry（Predicate predicate）
                作用：出现错误后，判断是否需要重新发送数据（若需要重新发送& 持续遇到错误，则持续重试）
                参数 = 判断逻辑
                拦截错误后，判断当前错误是否需要重新发送请求，return false：不重新发送数据，调用onError方法
                                                        return true: 重新发送数据

                4. retry（new BiPredicate<Integer, Throwable>）
                作用：出现错误后，判断是否需要重新发送数据（若需要重新发送 & 持续遇到错误，则持续重试
                参数 =  判断逻辑（传入当前重试次数 & 异常错误信息）
                拦截错误后，判断当前重试次数是否需要重新发送请求，return false：不重新发送数据，调用onError方法
                                                           return true: 重新发送数据

                5. retry（long time,Predicate predicate）
                作用：出现错误后，判断是否需要重新发送数据（具备重试次数限制
                参数 = 设置重试次数 & 判断逻辑
                拦截错误后，判断当前错误信息是否需要重新发送请求，return false：不重新发送数据，调用onError方法
                                                           return true: 重新发送数据 最多重复time次
            */
    }

    /**
     * 出现错误后，判断是否需要重新发送数据
     */
    private void rxjavaRetryWhen() {
        /*
             1. 新的被观察者 Observable发送的事件--->>>若返回的Observable发送的事件 = Error事件，则原始的Observable不重新发送事件
             该异常错误信息可在观察者中的onError（）中获得
             return Observable.error(new Throwable("retryWhen终止啦"));

             2. 新的被观察者 Observable发送的事件--->>> 若返回的Observable发送的事件 = Next事件，则原始的Observable重新发送事件（若持续遇到错误，则持续重试）
             return Observable.just(1);
         */
        Observable.create(new ObservableOnSubscribe<Integer>() {
            @Override
            public void subscribe(ObservableEmitter<Integer> e) throws Exception {
                e.onNext(1);
                e.onNext(2);
                e.onError(new Exception("发生错误了"));
                e.onNext(3);
            }
        })
                // 遇到error事件才会回调
                .retryWhen(new Function<Observable<Throwable>, ObservableSource<?>>() {

                    @Override
                    public ObservableSource<?> apply(@NonNull Observable<Throwable> throwableObservable) throws Exception {
                        // 参数Observable<Throwable>中的泛型 = 上游操作符抛出的异常，可通过该条件来判断异常的类型
                        // 返回Observable<?> = 新的被观察者 Observable（任意类型）
                        // 此处有两种情况：
                        // 1. 若 新的被观察者 Observable发送的事件 = Error事件，那么 原始Observable则不重新发送事件：
                        // 2. 若 新的被观察者 Observable发送的事件 = Next事件 ，那么原始的Observable则重新发送事件：
                        return throwableObservable.flatMap(new Function<Throwable, ObservableSource<?>>() {
                            @Override
                            public ObservableSource<?> apply(@NonNull Throwable throwable) throws Exception {

                                // 1. 若返回的Observable发送的事件 = Error事件，则原始的Observable不重新发送事件
                                // 该异常错误信息可在观察者中的onError（）中获得
                                return Observable.error(new Throwable("retryWhen终止啦"));

                                // 2. 若返回的Observable发送的事件 = Next事件，则原始的Observable重新发送事件（若持续遇到错误，则持续重试）
                                // return Observable.just(1);
                            }
                        });

                    }
                })
                .subscribe(new Observer<Integer>() {
                    @Override
                    public void onSubscribe(Disposable d) {

                    }

                    @Override
                    public void onNext(Integer value) {
                        Log.d("123===", "接收到了事件" + value);
                    }

                    @Override
                    public void onError(Throwable e) {
                        Log.d("123===", "对Error事件作出响应" + e.toString());
                        // 获取异常错误信息
                    }

                    @Override
                    public void onComplete() {
                        Log.d("123===", "对Complete事件作出响应");
                    }
                });
    }

    /**
     * 重复不断地发送被观察者事件
     */
    private void rxjavaRepeat() {
        /*
             不传入参数 = 重复发送次数 = 无限次
             repeat（）；
             传入参数 = 重复发送次数有限
             repeatWhen（Integer int ）；

             注：
             1. 接收到.onCompleted()事件后，触发重新订阅 & 发送
             2. 默认运行在一个新的线程上
         */
    }

    /**
     * 有条件地、重复发送 被观察者事件
     */
    private void rxjavaRepeatWhen() {
        /*
            若新被观察者（Observable）返回1个Complete / Error事件，则不
            若新被观察者（Observable）返回其余事件时，则重新订阅 & 发送原来的 Observable
         */
        Observable.just(1, 2, 4)
                .repeatWhen(new Function<Observable<Object>, ObservableSource<?>>() {
                    @Override
                    // 在Function函数中，必须对输入的 Observable<Object>进行处理，这里我们使用的是flatMap操作符接收上游的数据
                    public ObservableSource<?> apply(@NonNull Observable<Object> objectObservable) throws Exception {
                        // 将原始 Observable 停止发送事件的标识（Complete（） /  Error（））转换成1个 Object 类型数据传递给1个新被观察者（Observable）
                        // 以此决定是否重新订阅 & 发送原来的 Observable
                        // 此处有2种情况：
                        // 1. 若新被观察者（Observable）返回1个Complete（） /  Error（）事件，则不重新订阅 & 发送原来的 Observable
                        // 2. 若新被观察者（Observable）返回其余事件，则重新订阅 & 发送原来的 Observable
                        return objectObservable.flatMap(new Function<Object, ObservableSource<?>>() {
                            @Override
                            public ObservableSource<?> apply(@NonNull Object throwable) throws Exception {

                                // 情况1：若新被观察者（Observable）返回1个Complete（） /  Error（）事件，则不重新订阅 & 发送原来的 Observable
//                                return Observable.empty();
                                // Observable.empty() = 发送Complete事件，但不会回调观察者的onComplete（）

                                return Observable.error(new Throwable("不再重新订阅事件"));
                                // 返回Error事件 = 回调onError（）事件，并接收传过去的错误信息。

                                // 情况2：若新被观察者（Observable）返回其余事件，则重新订阅 & 发送原来的 Observable
//                                 return Observable.just(1);
                                // 仅仅是作为1个触发重新订阅被观察者的通知，发送的是什么数据并不重要，只要不是Complete（） /  Error（）事件
                            }
                        });

                    }
                })
                .subscribe(new Observer<Integer>() {
                    @Override
                    public void onSubscribe(Disposable d) {
                        Log.d("123===", "开始采用subscribe连接");
                    }

                    @Override
                    public void onNext(Integer value) {
                        Log.d("123===", "接收到了事件" + value);
                    }

                    @Override
                    public void onError(Throwable e) {
                        Log.d("123===", "对Error事件作出响应：" + e.toString());
                    }

                    @Override
                    public void onComplete() {
                        Log.d("123===", "对Complete事件作出响应");
                    }

                });
    }
```
